server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.121.100:3306/guli_pms
    username: root
    password: 123456
  redis:
    host: 192.168.121.100
    port: 6379
  rabbitmq:
    host: 192.168.121.100
    port: 5672
    virtual-host: /abigtomato
    username: guest
    password: guest

item:
  rabbitmq:
    exchange: SHOP-PMS-EXCHANGE

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml