server:
  port: 8092

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
  redis:
    host: 192.168.121.100
    port: 6379
  rabbitmq:
    host: 192.168.121.100
    virtual-host: /abigtomato
    username: guest
    password: guest

