server:
  port: 8089

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100
  redis:
    host: 192.168.121.100
    port: 6379
    timeout: 5000 # 连接超时，毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 # 连接池最大等行时间，-1没有限制
  datasource:
    druid:
      url: jdbc:mysql://192.168.121.100:3306/guli_ums
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  # 初始建立连接数量
      minIdle: 5  # 最小连接数量
      maxActive: 20 # 最大连接数量
      maxWait: 10000  # 获取连接最大等待时间，毫秒
      testOnBorrow: true # 申请连接时检测连接是否有效
      testOnReturn: false # 归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 # 配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  # 连接在连接池的最小生存时间（毫秒）

# 自定义配置
auth:
  tokenValiditySeconds: 1200  # token存储到redis中的过期时间
  clientId: XcWebApp      # oauth2客户端id（需要在oauth2相关表中设置）
  clientSecret: XcWebApp  # oauth2客户端密码
  cookieDomain: shop.com  # cookie作用域名
  cookieMaxAge: -1        # cookie存活时间（关闭浏览器失效）

# 认证服务相关配置
encrypt:
  # 证书配置
  key-store:
    location: classpath:/shop.keystore  # 证书路径（包含私钥）
    secret: 123456    # 密钥库密码
    alias: skey       # 别名
    password: 123456  # 密钥密码

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml