server:
  port: 8888

spring:
  application:
    name: shop-gateway
  redis:
    host: 192.168.121.100
    port: 6379
    timeout: 5000 #连接超时 毫秒
    jedis:
      pool:
        maxActive: 3
        maxIdle: 3
        minIdle: 1
        maxWait: -1 #连接池最大等行时间 -1没有限制
  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
    # 网关配置
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: index-route
          uri: lb://index-service
          predicates:
            - Path=/api/index/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}