server:
  port: 8086

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.100:8848
  elasticsearch:
    rest:
      uris: http://192.168.121.100:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.121.100
    port: 5672
    virtual-host: /abigtomato
    username: guest
    password: guest
